# Copyright (C) 2010-2015 Cuckoo Foundation.
# This file is part of Cuckoo Sandbox - http://www.cuckoosandbox.org
# See the file 'docs/LICENSE' for copying permission.

"""from_dockoo_to_0_2

Revision ID: d828880a327
Revises: fb22abd7c77
Create Date: 2015-12-04 00:48:17.590395

"""

# revision identifiers, used by Alembic.
revision = 'd828880a327'
down_revision = 'fb22abd7c77'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
