# Copyright (C) 2010-2015 Cuckoo Foundation.
# This file is part of Cuckoo Sandbox - http://www.cuckoosandbox.org
# See the file 'docs/LICENSE' for copying permission.

"""testautogenerate

Revision ID: fb22abd7c77
Revises: 1070cd314622
Create Date: 2015-12-04 00:35:16.947919

"""

# revision identifiers, used by Alembic.
revision = 'fb22abd7c77'
down_revision = '1070cd314622'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('docker_images')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docker_images',
    sa.Column('tasks_id', sa.INTEGER(), nullable=False),
    sa.Column('docker_img', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('tasks_id'),
    sa.UniqueConstraint('docker_img')
    )
    ### end Alembic commands ###
